export var SIDES;
(function (SIDES) {
    SIDES[SIDES["LEFT"] = 0] = "LEFT";
    SIDES[SIDES["TOP"] = 1] = "TOP";
    SIDES[SIDES["RIGHT"] = 2] = "RIGHT";
    SIDES[SIDES["BOTTOM"] = 3] = "BOTTOM";
})(SIDES || (SIDES = {}));
export var ROLES;
(function (ROLES) {
    ROLES[ROLES["BACK"] = 0] = "BACK";
    ROLES[ROLES["FRONT"] = 1] = "FRONT";
})(ROLES || (ROLES = {}));
export var BALL_TYPES;
(function (BALL_TYPES) {
    BALL_TYPES[BALL_TYPES["BASIC"] = 0] = "BASIC";
    BALL_TYPES[BALL_TYPES["EXPAND"] = 1] = "EXPAND";
    BALL_TYPES[BALL_TYPES["SHRINK"] = 2] = "SHRINK";
    BALL_TYPES[BALL_TYPES["SPEED_UP"] = 3] = "SPEED_UP";
    BALL_TYPES[BALL_TYPES["SLOW_DOWN"] = 4] = "SLOW_DOWN";
    BALL_TYPES[BALL_TYPES["EXTRA_BALL"] = 5] = "EXTRA_BALL";
    BALL_TYPES[BALL_TYPES["RESTORE"] = 6] = "RESTORE";
    BALL_TYPES[BALL_TYPES["DESTROY"] = 7] = "DESTROY";
    BALL_TYPES[BALL_TYPES["MASSIVE_DAMAGE"] = 8] = "MASSIVE_DAMAGE";
    BALL_TYPES[BALL_TYPES["MYSTERY"] = 9] = "MYSTERY";
    BALL_TYPES[BALL_TYPES["BALL_TYPE_AM"] = 10] = "BALL_TYPE_AM";
})(BALL_TYPES || (BALL_TYPES = {}));
